import { Video, Comment, AudioTrack, ChannelStats, ChartDataPoint, TrafficSource, SubtitleTrack } from "./types";

export const initialChannelStats: ChannelStats = {
  name: "Dev Creator Studio",
  handle: "@devcreatorstudio",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
  banner: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1600",
  subscribers: 124580,
  subscriberChange28Days: 3420,
  views28Days: 1845200,
  watchTimeHours28Days: 94200,
  estimatedRevenue28Days: 3450.8,
  realtime48HoursViews: 84320,
  realtime60MinsViews: 1890,
};

export const initialVideos: Video[] = [
  {
    id: "v1",
    title: "Building Full-Stack AI Apps in 2026 (Complete Roadmap & Code)",
    description: "Learn how to build production-ready AI applications using Node.js, Express, React, and Gemini 3.6 API models. Step-by-step tutorial for beginner and intermediate developers.",
    thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    duration: "18:42",
    visibility: "Public",
    monetization: true,
    adSuitabilityStatus: "green",
    restrictions: "None",
    uploadDate: "Jul 24, 2026",
    views: 45890,
    commentsCount: 342,
    likes: 3820,
    dislikes: 42,
    likePercentage: 98.9,
    ctr: 8.4,
    avgViewDuration: "7:15",
    tags: ["AI", "React", "NodeJS", "Fullstack", "Gemini API", "Coding Roadmap"],
    category: "Science & Technology",
  },
  {
    id: "v2",
    title: "Why Senior Developers Hate Clean Code (Unpopular Tech Opinion)",
    description: "In this video we discuss premature abstraction, over-engineering in React components, and why simple procedural code often wins in fast-moving startups.",
    thumbnail: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    duration: "12:15",
    visibility: "Public",
    monetization: true,
    adSuitabilityStatus: "yellow",
    restrictions: "None",
    uploadDate: "Jul 18, 2026",
    views: 128400,
    commentsCount: 1120,
    likes: 11200,
    dislikes: 310,
    likePercentage: 97.3,
    ctr: 11.2,
    avgViewDuration: "6:48",
    tags: ["Clean Code", "Software Engineering", "React", "Tech Career"],
    category: "Science & Technology",
  },
  {
    id: "v3",
    title: "I Replaced My Database with Local-First SQLite in 10 Minutes",
    description: "Exploring SQLite in browser and edge runtime. Benchmarking speed, offline sync, and real-time state management.",
    thumbnail: "https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&q=80&w=800",
    duration: "14:05",
    visibility: "Public",
    monetization: true,
    adSuitabilityStatus: "green",
    restrictions: "None",
    uploadDate: "Jul 10, 2026",
    views: 94200,
    commentsCount: 560,
    likes: 7400,
    dislikes: 120,
    likePercentage: 98.4,
    ctr: 9.1,
    avgViewDuration: "5:50",
    tags: ["SQLite", "Database", "WebDev", "Backend"],
    category: "Science & Technology",
  },
  {
    id: "v4",
    title: "Late Night Lo-Fi Coding Session with Chill Background Beats",
    description: "Relaxed coding livestream replay with background ambient music.",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
    duration: "45:10",
    visibility: "Public",
    monetization: false,
    adSuitabilityStatus: "yellow",
    restrictions: "Copyright claim",
    copyrightClaimDetails: {
      id: "cclaim-101",
      videoId: "v4",
      claimedTrack: "Midnight Chill Lounge Loop",
      claimOwner: "Sony Music Entertainment / Content ID",
      claimType: "Audio track match",
      timestampRange: "02:14 - 05:30",
      channelImpact: "Not affected (No channel strikes)",
      monetizationImpact: "Ad revenue shared with copyright owner",
      status: "Active claim",
    },
    uploadDate: "Jul 02, 2026",
    views: 62400,
    commentsCount: 210,
    likes: 4200,
    dislikes: 45,
    likePercentage: 98.9,
    ctr: 6.8,
    avgViewDuration: "18:20",
    tags: ["LoFi", "Coding", "Music", "Chill Beats"],
    category: "Entertainment",
  },
  {
    id: "v5",
    title: "10 VS Code Extensions Every Developer MUST Have in 2026",
    description: "Boost your developer productivity with these essential VS Code extensions for AI autocomplete, git visualization, and theme customization.",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
    duration: "09:30",
    visibility: "Public",
    monetization: true,
    restrictions: "None",
    uploadDate: "Jun 28, 2026",
    views: 210500,
    commentsCount: 890,
    likes: 18400,
    dislikes: 240,
    likePercentage: 98.7,
    ctr: 12.8,
    avgViewDuration: "4:55",
    tags: ["VS Code", "Developer Tools", "Productivity", "Coding Tips"],
    category: "Science & Technology",
  },
  {
    id: "v6",
    title: "Tailwind CSS v4 Features You Didn't Know Existed!",
    description: "A deep dive into zero-config Vite setup, dynamic CSS variables, built-in container queries, and performance gains in Tailwind v4.",
    thumbnail: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=800",
    duration: "08:12",
    visibility: "Public",
    monetization: true,
    restrictions: "None",
    uploadDate: "Jun 15, 2026",
    views: 89400,
    commentsCount: 410,
    likes: 6500,
    dislikes: 95,
    likePercentage: 98.5,
    ctr: 7.9,
    avgViewDuration: "4:10",
    tags: ["Tailwind", "CSS", "Frontend", "UI Design"],
    category: "Education",
  },
  {
    id: "v7",
    title: "AI Agents Explained in 60 Seconds #shorts",
    description: "What is an autonomous AI agent? Here is how agentic loops work with tool calling and reasoning.",
    thumbnail: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&q=80&w=800",
    duration: "0:58",
    visibility: "Public",
    monetization: true,
    restrictions: "None",
    uploadDate: "Jul 20, 2026",
    views: 450200,
    commentsCount: 1840,
    likes: 34200,
    dislikes: 450,
    likePercentage: 98.7,
    ctr: 15.4,
    avgViewDuration: "0:52",
    tags: ["AI", "Shorts", "TechShorts", "Coding"],
    category: "Science & Technology",
    isShort: true,
  },
];

export const initialComments: Comment[] = [
  {
    id: "c1",
    videoId: "v1",
    videoTitle: "Building Full-Stack AI Apps in 2026 (Complete Roadmap & Code)",
    author: "Alex Rivers",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=100",
    text: "This roadmap is incredible! Loved the section on setting up Express proxy routes for the Gemini API. Could you make a follow-up video on webhooks?",
    timeAgo: "2 hours ago",
    likes: 48,
    heart: true,
    status: "published",
    subscriberCount: "12.4K subscribers",
  },
  {
    id: "c2",
    videoId: "v1",
    videoTitle: "Building Full-Stack AI Apps in 2026 (Complete Roadmap & Code)",
    author: "Sarah Chen",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100",
    text: "At 07:15 when you explained state persistence, that finally made React context click for me! Thank you so much for breaking it down.",
    timeAgo: "5 hours ago",
    likes: 29,
    heart: false,
    status: "published",
    subscriberCount: "1.2K subscribers",
  },
  {
    id: "c3",
    videoId: "v2",
    videoTitle: "Why Senior Developers Hate Clean Code (Unpopular Tech Opinion)",
    author: "CodeWithSam",
    avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&q=80&w=100",
    text: "100% agree! People focus so much on dry code that they end up creating impossible coupling. Simplicity > Premature Abstraction every time.",
    timeAgo: "1 day ago",
    likes: 182,
    heart: true,
    status: "published",
    subscriberCount: "45K subscribers",
  },
  {
    id: "c4",
    videoId: "v3",
    videoTitle: "I Replaced My Database with Local-First SQLite in 10 Minutes",
    author: "TechEnthusiast_99",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100",
    text: "Check out my channel for free crypto signals click http://bit.ly/fake-link",
    timeAgo: "3 hours ago",
    likes: 0,
    heart: false,
    status: "held_for_review",
    subscriberCount: "0 subscribers",
  },
];

export const initialAudioTracks: AudioTrack[] = [
  {
    id: "a1",
    title: "Cybernetic Horizon",
    artist: "Synthwave Audio",
    genre: "Electronic",
    mood: "Dramatic / Energetic",
    duration: "2:45",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    licenseType: "ProNax Audio Library",
    isStarred: true,
  },
  {
    id: "a2",
    title: "Lo-Fi Study Beats Vol. 4",
    artist: "ChillHop Studio",
    genre: "Hip-Hop & Rap",
    mood: "Calm / Relaxing",
    duration: "3:12",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    licenseType: "ProNax Audio Library",
    isStarred: false,
  },
  {
    id: "a3",
    title: "Acoustic Morning Sunshine",
    artist: "Folk Vibe",
    genre: "Acoustic",
    mood: "Happy / Inspiring",
    duration: "2:18",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    licenseType: "ProNax Audio Library",
    isStarred: true,
  },
  {
    id: "a4",
    title: "Epic Trailer Rise",
    artist: "Cinematic Elements",
    genre: "Cinematic",
    mood: "Suspense / Action",
    duration: "1:55",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    licenseType: "Attribution Required",
    isStarred: false,
  },
  {
    id: "a5",
    title: "Minimalist Coding Flow",
    artist: "Ambient Lab",
    genre: "Ambient",
    mood: "Focus / Mindful",
    duration: "4:02",
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    licenseType: "ProNax Audio Library",
    isStarred: false,
  },
];

export const analyticsChartData: ChartDataPoint[] = [
  { date: "Jul 1", views: 42000, watchTime: 2100, subscribers: 85, revenue: 84.50 },
  { date: "Jul 4", views: 54000, watchTime: 2800, subscribers: 110, revenue: 102.20 },
  { date: "Jul 7", views: 49000, watchTime: 2450, subscribers: 92, revenue: 95.80 },
  { date: "Jul 10", views: 68000, watchTime: 3400, subscribers: 145, revenue: 135.40 },
  { date: "Jul 13", views: 61000, watchTime: 3100, subscribers: 128, revenue: 122.00 },
  { date: "Jul 16", views: 88000, watchTime: 4500, subscribers: 195, revenue: 182.30 },
  { date: "Jul 19", views: 112000, watchTime: 5900, subscribers: 260, revenue: 245.10 },
  { date: "Jul 22", views: 95000, watchTime: 4800, subscribers: 210, revenue: 198.60 },
  { date: "Jul 25", views: 125000, watchTime: 6400, subscribers: 310, revenue: 285.90 },
  { date: "Jul 28", views: 138000, watchTime: 7100, subscribers: 342, revenue: 312.40 },
];

export const trafficSourcesData: TrafficSource[] = [
  { name: "Pronax Search", percentage: 42.5, views: 784200 },
  { name: "Suggested Videos", percentage: 28.3, views: 522100 },
  { name: "Browse Features (Home)", percentage: 18.2, views: 335800 },
  { name: "External (Twitter, Reddit, Google)", percentage: 6.8, views: 125400 },
  { name: "Direct or Unknown", percentage: 4.2, views: 77700 },
];

export const initialSubtitleTracks: SubtitleTrack[] = [
  {
    id: "sub-1",
    videoId: "v1",
    language: "English (Video language)",
    isAutomatic: false,
    status: "Published",
    captions: [
      { id: "c-1", startTime: "00:00:01.000", endTime: "00:00:04.500", text: "Welcome back to Dev Creator Studio! Today we build full-stack AI apps." },
      { id: "c-2", startTime: "00:00:05.000", endTime: "00:00:09.200", text: "We'll cover Node.js backend proxy setup and Gemini 3.6 API integration." },
      { id: "c-3", startTime: "00:00:09.800", endTime: "00:00:14.000", text: "Let me show you the project architecture on screen right now." },
    ],
  },
  {
    id: "sub-2",
    videoId: "v1",
    language: "Spanish (Latin America)",
    isAutomatic: true,
    status: "Published",
    captions: [
      { id: "cs-1", startTime: "00:00:01.000", endTime: "00:00:04.500", text: "¡Bienvenidos de nuevo a Dev Creator Studio! Hoy desarrollaremos aplicaciones de IA." },
      { id: "cs-2", startTime: "00:00:05.000", endTime: "00:00:09.200", text: "Cubriremos la configuración del servidor Node.js y la API de Gemini." },
    ],
  },
  {
    id: "sub-3",
    videoId: "v2",
    language: "English (Automatic)",
    isAutomatic: true,
    status: "Published",
    captions: [
      { id: "c2-1", startTime: "00:00:00.500", endTime: "00:00:03.800", text: "Why do senior developers often push back against premature clean code?" },
      { id: "c2-2", startTime: "00:00:04.200", endTime: "00:00:08.500", text: "In fast-moving startups, over-abstraction creates maintenance nightmare." },
    ],
  },
];
