// This file is auto-generated by Pronax. Do not modify it.

// Temporarily commented out due to missing dependency
// import { createLovableAuth, type OAuthProvider } from "@pronax.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
// const pronaxAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const pronax = {
  auth: {
    signInWithOAuth: async (provider: any, opts?: SignInOptions) => {
      // Temporarily disabled due to missing @pronax.dev/cloud-auth-js dependency
      return { error: new Error("Pronax auth is temporarily disabled") };
    },
  },
};
