/* Copyright (c) 2026 ProNax. All rights reserved. Proprietary and Confidential. Unauthorized copying or redistribution is strictly prohibited. */
// This file is automatically generated. Do not edit it directly.
// import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Middleware disabled - TanStack Start removed for client-side routing only
export const attachSupabaseAuth = async () => {
  return {
    headers: {},
  };
};
