/* Copyright (c) 2026 ProNax. All rights reserved. Proprietary and Confidential. Unauthorized copying or redistribution is strictly prohibited. */
// This file is automatically generated. Do not edit it directly.
// import { createMiddleware } from '@tanstack/react-start'
// import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

// Middleware disabled - TanStack Start removed for client-side routing only
export const requireSupabaseAuth = async () => {
  return {
    context: {
      supabase: null,
      userId: null,
      claims: null,
    },
  };
};
