/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppealRouteImport } from './routes/appeal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LikesRouteImport } from './routes/likes'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PronaxStudioRouteImport } from './routes/pronax-studio'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StudioLegacyRouteImport } from './routes/studio-legacy'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminAdminRouteImport } from './routes/admin._admin'
import { Route as ChannelHandleRouteImport } from './routes/channel.$handle'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LivePlaybackIdRouteImport } from './routes/live.$playbackId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileHandleRouteImport } from './routes/profile.$handle'
import { Route as ShortsIndexRouteImport } from './routes/shorts.index'
import { Route as ShortsIdRouteImport } from './routes/shorts.$id'
import { Route as SoundIdRouteImport } from './routes/sound.$id'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioSplatRouteImport } from './routes/studio.$'
import { Route as StudioDashboardRouteImport } from './routes/studio.dashboard'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as AdminAdminIndexRouteImport } from './routes/admin._admin/index'
import { Route as AdminAdminEngineRouteImport } from './routes/admin._admin/engine'
import { Route as PronaxOauthConsentRouteImport } from './routes/pronax.oauth.consent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: '/appeal',
  path: '/appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LikesRoute = LikesRouteImport.update({
  id: '/likes',
  path: '/likes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PronaxStudioRoute = PronaxStudioRouteImport.update({
  id: '/pronax-studio',
  path: '/pronax-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioLegacyRoute = StudioLegacyRouteImport.update({
  id: '/studio-legacy',
  path: '/studio-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelHandleRoute = ChannelHandleRouteImport.update({
  id: '/channel/$handle',
  path: '/channel/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivePlaybackIdRoute = LivePlaybackIdRouteImport.update({
  id: '/live/$playbackId',
  path: '/live/$playbackId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHandleRoute = ProfileHandleRouteImport.update({
  id: '/profile/$handle',
  path: '/profile/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsIndexRoute = ShortsIndexRouteImport.update({
  id: '/shorts/',
  path: '/shorts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsIdRoute = ShortsIdRouteImport.update({
  id: '/shorts/$id',
  path: '/shorts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundIdRoute = SoundIdRouteImport.update({
  id: '/sound/$id',
  path: '/sound/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioSplatRoute = StudioSplatRouteImport.update({
  id: '/studio/$',
  path: '/studio/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioDashboardRoute = StudioDashboardRouteImport.update({
  id: '/studio/dashboard',
  path: '/studio/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEngineRoute = AdminAdminEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => AdminAdminRoute,
} as any)
const PronaxOauthConsentRoute = PronaxOauthConsentRouteImport.update({
  id: '/pronax/oauth/consent',
  path: '/pronax/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRoute
  '/likes': typeof LikesRoute
  '/playlists': typeof PlaylistsRoute
  '/privacy': typeof PrivacyRoute
  '/pronax-studio': typeof PronaxStudioRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/studio-legacy': typeof StudioLegacyRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/channel/$handle': typeof ChannelHandleRoute
  '/live/$playbackId': typeof LivePlaybackIdRoute
  '/p/$slug': typeof PSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/shorts/$id': typeof ShortsIdRoute
  '/sound/$id': typeof SoundIdRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/watch/$id': typeof WatchIdRoute
  '/live/': typeof LiveIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/shorts/': typeof ShortsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/admin/engine': typeof AdminAdminEngineRoute
  '/pronax/oauth/consent': typeof PronaxOauthConsentRoute
  '/admin/': typeof AdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRoute
  '/likes': typeof LikesRoute
  '/playlists': typeof PlaylistsRoute
  '/privacy': typeof PrivacyRoute
  '/pronax-studio': typeof PronaxStudioRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/studio-legacy': typeof StudioLegacyRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/channel/$handle': typeof ChannelHandleRoute
  '/live/$playbackId': typeof LivePlaybackIdRoute
  '/p/$slug': typeof PSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/shorts/$id': typeof ShortsIdRoute
  '/sound/$id': typeof SoundIdRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/watch/$id': typeof WatchIdRoute
  '/live': typeof LiveIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/shorts': typeof ShortsIndexRoute
  '/studio': typeof StudioIndexRoute
  '/admin/engine': typeof AdminAdminEngineRoute
  '/pronax/oauth/consent': typeof PronaxOauthConsentRoute
  '/admin': typeof AdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeal': typeof AppealRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/history': typeof HistoryRoute
  '/likes': typeof LikesRoute
  '/playlists': typeof PlaylistsRoute
  '/privacy': typeof PrivacyRoute
  '/pronax-studio': typeof PronaxStudioRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/studio-legacy': typeof StudioLegacyRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/trending': typeof TrendingRoute
  '/upload': typeof UploadRoute
  '/wallet': typeof WalletRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/channel/$handle': typeof ChannelHandleRoute
  '/live/$playbackId': typeof LivePlaybackIdRoute
  '/p/$slug': typeof PSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/profile/$handle': typeof ProfileHandleRoute
  '/shorts/$id': typeof ShortsIdRoute
  '/sound/$id': typeof SoundIdRoute
  '/studio/$': typeof StudioSplatRoute
  '/studio/dashboard': typeof StudioDashboardRoute
  '/watch/$id': typeof WatchIdRoute
  '/live/': typeof LiveIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/shorts/': typeof ShortsIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/admin/_admin/engine': typeof AdminAdminEngineRoute
  '/pronax/oauth/consent': typeof PronaxOauthConsentRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeal'
    | '/auth'
    | '/explore'
    | '/history'
    | '/likes'
    | '/playlists'
    | '/privacy'
    | '/pronax-studio'
    | '/saved'
    | '/search'
    | '/security'
    | '/settings'
    | '/studio-legacy'
    | '/subscriptions'
    | '/trending'
    | '/upload'
    | '/wallet'
    | '/admin'
    | '/channel/$handle'
    | '/live/$playbackId'
    | '/p/$slug'
    | '/playlist/$id'
    | '/profile/$handle'
    | '/shorts/$id'
    | '/sound/$id'
    | '/studio/$'
    | '/studio/dashboard'
    | '/watch/$id'
    | '/live/'
    | '/profile/'
    | '/shorts/'
    | '/studio/'
    | '/admin/engine'
    | '/pronax/oauth/consent'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeal'
    | '/auth'
    | '/explore'
    | '/history'
    | '/likes'
    | '/playlists'
    | '/privacy'
    | '/pronax-studio'
    | '/saved'
    | '/search'
    | '/security'
    | '/settings'
    | '/studio-legacy'
    | '/subscriptions'
    | '/trending'
    | '/upload'
    | '/wallet'
    | '/channel/$handle'
    | '/live/$playbackId'
    | '/p/$slug'
    | '/playlist/$id'
    | '/profile/$handle'
    | '/shorts/$id'
    | '/sound/$id'
    | '/studio/$'
    | '/studio/dashboard'
    | '/watch/$id'
    | '/live'
    | '/profile'
    | '/shorts'
    | '/studio'
    | '/admin/engine'
    | '/pronax/oauth/consent'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/appeal'
    | '/auth'
    | '/explore'
    | '/history'
    | '/likes'
    | '/playlists'
    | '/privacy'
    | '/pronax-studio'
    | '/saved'
    | '/search'
    | '/security'
    | '/settings'
    | '/studio-legacy'
    | '/subscriptions'
    | '/trending'
    | '/upload'
    | '/wallet'
    | '/admin/_admin'
    | '/channel/$handle'
    | '/live/$playbackId'
    | '/p/$slug'
    | '/playlist/$id'
    | '/profile/$handle'
    | '/shorts/$id'
    | '/sound/$id'
    | '/studio/$'
    | '/studio/dashboard'
    | '/watch/$id'
    | '/live/'
    | '/profile/'
    | '/shorts/'
    | '/studio/'
    | '/admin/_admin/engine'
    | '/pronax/oauth/consent'
    | '/admin/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealRoute: typeof AppealRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  HistoryRoute: typeof HistoryRoute
  LikesRoute: typeof LikesRoute
  PlaylistsRoute: typeof PlaylistsRoute
  PrivacyRoute: typeof PrivacyRoute
  PronaxStudioRoute: typeof PronaxStudioRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  StudioLegacyRoute: typeof StudioLegacyRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TrendingRoute: typeof TrendingRoute
  UploadRoute: typeof UploadRoute
  WalletRoute: typeof WalletRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  ChannelHandleRoute: typeof ChannelHandleRoute
  LivePlaybackIdRoute: typeof LivePlaybackIdRoute
  PSlugRoute: typeof PSlugRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  ProfileHandleRoute: typeof ProfileHandleRoute
  ShortsIdRoute: typeof ShortsIdRoute
  SoundIdRoute: typeof SoundIdRoute
  StudioSplatRoute: typeof StudioSplatRoute
  StudioDashboardRoute: typeof StudioDashboardRoute
  WatchIdRoute: typeof WatchIdRoute
  LiveIndexRoute: typeof LiveIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ShortsIndexRoute: typeof ShortsIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  PronaxOauthConsentRoute: typeof PronaxOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal': {
      id: '/appeal'
      path: '/appeal'
      fullPath: '/appeal'
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/likes': {
      id: '/likes'
      path: '/likes'
      fullPath: '/likes'
      preLoaderRoute: typeof LikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronax-studio': {
      id: '/pronax-studio'
      path: '/pronax-studio'
      fullPath: '/pronax-studio'
      preLoaderRoute: typeof PronaxStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-legacy': {
      id: '/studio-legacy'
      path: '/studio-legacy'
      fullPath: '/studio-legacy'
      preLoaderRoute: typeof StudioLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$handle': {
      id: '/channel/$handle'
      path: '/channel/$handle'
      fullPath: '/channel/$handle'
      preLoaderRoute: typeof ChannelHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$playbackId': {
      id: '/live/$playbackId'
      path: '/live/$playbackId'
      fullPath: '/live/$playbackId'
      preLoaderRoute: typeof LivePlaybackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$handle': {
      id: '/profile/$handle'
      path: '/profile/$handle'
      fullPath: '/profile/$handle'
      preLoaderRoute: typeof ProfileHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/': {
      id: '/shorts/'
      path: '/shorts'
      fullPath: '/shorts/'
      preLoaderRoute: typeof ShortsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/$id': {
      id: '/shorts/$id'
      path: '/shorts/$id'
      fullPath: '/shorts/$id'
      preLoaderRoute: typeof ShortsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound/$id': {
      id: '/sound/$id'
      path: '/sound/$id'
      fullPath: '/sound/$id'
      preLoaderRoute: typeof SoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$': {
      id: '/studio/$'
      path: '/studio/$'
      fullPath: '/studio/$'
      preLoaderRoute: typeof StudioSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/dashboard': {
      id: '/studio/dashboard'
      path: '/studio/dashboard'
      fullPath: '/studio/dashboard'
      preLoaderRoute: typeof StudioDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/engine': {
      id: '/admin/_admin/engine'
      path: '/engine'
      fullPath: '/admin/engine'
      preLoaderRoute: typeof AdminAdminEngineRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/pronax/oauth/consent': {
      id: '/pronax/oauth/consent'
      path: '/pronax/oauth/consent'
      fullPath: '/pronax/oauth/consent'
      preLoaderRoute: typeof PronaxOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminEngineRoute: typeof AdminAdminEngineRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminEngineRoute: AdminAdminEngineRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealRoute: AppealRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  HistoryRoute: HistoryRoute,
  LikesRoute: LikesRoute,
  PlaylistsRoute: PlaylistsRoute,
  PrivacyRoute: PrivacyRoute,
  PronaxStudioRoute: PronaxStudioRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  StudioLegacyRoute: StudioLegacyRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TrendingRoute: TrendingRoute,
  UploadRoute: UploadRoute,
  WalletRoute: WalletRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  ChannelHandleRoute: ChannelHandleRoute,
  LivePlaybackIdRoute: LivePlaybackIdRoute,
  PSlugRoute: PSlugRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  ProfileHandleRoute: ProfileHandleRoute,
  ShortsIdRoute: ShortsIdRoute,
  SoundIdRoute: SoundIdRoute,
  StudioSplatRoute: StudioSplatRoute,
  StudioDashboardRoute: StudioDashboardRoute,
  WatchIdRoute: WatchIdRoute,
  LiveIndexRoute: LiveIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ShortsIndexRoute: ShortsIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  PronaxOauthConsentRoute: PronaxOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
