/*
 * ProNax - Supabase Client Configuration
 * Copyright (c) 2026. All rights reserved.
 * 
 * Commercial Single-End Product License.
 * Reselling, distributing, sublicensing, or sharing this codebase 
 * or any portion thereof without explicit written permission is strictly prohibited.
 */

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


// Used only when credentials are absent (e.g. local/preview sandbox without env vars).
// Requests to this host simply fail, which supabase-js surfaces as `{ data: null, error }`
// instead of throwing during module initialisation and blanking the whole app.
const OFFLINE_URL = 'https://offline.invalid';
const OFFLINE_KEY = 'offline-placeholder-key';

function readEnv(viteKey: string, nodeKey: string): string | undefined {
  const fromVite = (import.meta.env as Record<string, string | undefined>)[viteKey];
  if (fromVite) return fromVite;
  try {
    return typeof process !== 'undefined' ? process.env?.[nodeKey] : undefined;
  } catch {
    return undefined;
  }
}

function isUsableUrl(value: string | undefined): value is string {
  return !!value && /^https?:\/\/[^\s]+$/i.test(value);
}

export const isSupabaseConfigured = (): boolean =>
  isUsableUrl(readEnv('VITE_SUPABASE_URL', 'SUPABASE_URL')) &&
  !!readEnv('VITE_SUPABASE_PUBLISHABLE_KEY', 'SUPABASE_PUBLISHABLE_KEY');

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const envUrl = readEnv('VITE_SUPABASE_URL', 'SUPABASE_URL');
  const envKey = readEnv('VITE_SUPABASE_PUBLISHABLE_KEY', 'SUPABASE_PUBLISHABLE_KEY');

  const configured = isUsableUrl(envUrl) && !!envKey;

  if (!configured) {
    const missing = [
      ...(!isUsableUrl(envUrl) ? ['SUPABASE_URL'] : []),
      ...(!envKey ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    console.warn(
      `[Supabase] Missing or invalid environment variable(s): ${missing.join(', ')}. ` +
        `Running in offline mode — data requests will return errors instead of crashing the app.`,
    );
  }

  const SUPABASE_URL = configured ? (envUrl as string) : OFFLINE_URL;
  const SUPABASE_PUBLISHABLE_KEY = configured ? (envKey as string) : OFFLINE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

